### ISSUE TITLE
bug:not match the actual name "react-native-share"

### ISSUE THREAD

**Issue by zmfang** [react-native-oh-library/react-native-share#13]
### 描述 / Description

<img width="1878" alt="image" src="https://github.com/user-attachments/assets/62d16996-60ac-482c-a04a-45803f5e3454">

---

## 问题描述

在项目中尝试 link 包 `@react-native-oh-tpl/react-native-share` 时出现 `name` 不匹配的错误。错误信息如下：

```plaintext
oh-package.json5" does not match the actual name "react-native-share" of its oh-package.json5
```

### 配置方式

在文档中使用以下方式进行 link：

```json
"@react-native-oh-tpl/react-native-share": "file:../../node_modules/@react-native-oh-tpl/react-native-share/harmony/react_native_share.har"
```

### 错误原因

该错误是由于 `react_native_share.har` 包中的 `oh-package.json5` 文件中 `name` 字段为 `"react-native-share"`，而不是 `@react-native-oh-tpl/react-native-share`，导致 link 不成功。

## 解决方案

修改 `harmony/entry/oh-package.json5` 中的导入为以下格式，使其与实际 `name` 字段匹配：

```json
"react-native-share": "file:../../node_modules/@react-native-oh-tpl/react-native-share/harmony/react_native_share.har"
```

这样修改后，包可以成功同步。

---

### 库版本 / Library version

10.2.1-0.0.2

### React Native OpenHarmony version

0.72.27

### 构建类型 / Build type

None

### 设备 / Device

None

### 已悉知 / Acknowledgements

Yes

**Comment by ganghongli** [comment]
已修改react_native_share.har 包中的 oh-package.json5 文件中 name 字段为 "@react-native-oh-tpl/react-native-share"，请使用最新版本har包10.2.1-0.0.3，在entry/oh-package.json5文件中通过 "@react-native-oh-tpl/react-native-share": "file:../../node_modules/@react-native-oh-tpl/react-native-share/harmony/react_native_share.har" 引入
